# Name of workflow
name: Development workflow

# When workflow is triggered
on:
  pull_request:
    branches:
      - main

# Jobs to carry out
jobs:
  deploy:
    # Operating system to run job on
    runs-on: ubuntu-latest

    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1
      # Install NodeJS
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      # Run npm install and build on our code
      - run: npm install
      - run: npm run build
      # Deploy to Netlify using our dev secrets
      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: "kAS2t4qLaGitGYx_QcL5Su0iFEaKH2IvuMz2NnhO5lI"
          NETLIFY_SITE_ID: "44e58b1a-60a4-441c-b804-7bcf7023e48f"
        with:
          args: deploy --dir=build --prod
          secrets: '["kAS2t4qLaGitGYx_QcL5Su0iFEaKH2IvuMz2NnhO5lI", "44e58b1a-60a4-441c-b804-7bcf7023e48f"]'
